### ISSUE TITLE
Hello There ! What’s new ?

### ISSUE THREAD

**Issue by Zwordi** [gce-electronics/HA_RFPlayer#1]
Hi,

Glad to see an official project from gce around for this topics.

Any news to share ?

Thanks,

**Comment by Aohzan** [comment]
Hello,

Currently working slowly on it, need help if it's possible :slightly_smiling_face:

**Comment by Zwordi** [comment]
Hi, 

Sorry i’m not that good enough :) . Godspeed to you ! 🔥
