### ISSUE TITLE
En cours Beta 14

### ISSUE THREAD

**Issue by Doubledom45** [gce-electronics/HA_RFPlayer#10]
Version beta pour remonter OWL, EDISIO, OREGON
[Voir Issues 9](https://github.com/gce-electronics/HA_RFPlayer/issues/9)

[rfplayer.zip](https://github.com/gce-electronics/HA_RFPlayer/files/8240463/rfplayer.zip)

Possibilité d'envoyer une commande en mode Raw dans la partie commande dans l'outil de développement  (EDISIOFRAME ...), la création d'ID est possible avec le Raw Hexa de la commande 
 pour une commande Hors/Gel : EDISIOFRAME 0xDC 0xDB 0xE6 0x0C 0x01 0x16 0x21 0x05 0x00 0x61
le switch.edisioframe_0xdc_0xdb_0xe6_0x0c_0x01_0x16_0x21_0x05_0x00_0x61 sera créé

**Comment by Doubledom45** [comment]
New version
[rfplayer.zip](https://github.com/gce-electronics/HA_RFPlayer/files/8642665/rfplayer.zip)

Pour remontée ident plus simple Type Hygrométrique et Temperature pour Oregon
Implémentation autre Visonic RTS ....
Merci pour test et retour
![Capture d’écran 2022-05-06 191446](https://user-images.githubusercontent.com/97252459/167195349-f15293c7-da96-49f1-9db7-d5e267020d5f.png)

**Comment by Aohzan** [comment]
est-ce que tu peux créer une PR avec ton code pour voir les changes ?

**Comment by Doubledom45** [comment]
Je suis encore en train de faire des modifications.
Pour le "Jamming" l'info doit-être récupérée sur "sensor.jamming_0" et pas sur celui que tu as créé dans la partie diagnostic "jamming detection" [je n'ai pas modifié cette partie de `class RfplayerJammingSensor(RfplayerDevice):` de `/rfplayer/sensor.py` ]
Le slider de réglage fonctionne ( moi n'affiche pas la bonne valeur à droite) si réglage "0" arrête bien le "Jamming"

J'ai remodifier le `/rflib/rfpparser.py` pour la détection RTS et VISONIC 

Fichier de la béta 13  ( j'ai ajouté un fichier avec le nom `Béta 13` )
[rfplayer.zip](https://github.com/gce-electronics/HA_RFPlayer/files/8681731/rfplayer.zip)

**Comment by Doubledom45** [comment]
[rfplayer_beta14.zip](https://github.com/gce-electronics/HA_RFPlayer/files/8691625/rfplayer_beta14.zip)

Modification pour envoie protocole RTS, ou autres en mode RAW
![image](https://user-images.githubusercontent.com/97252459/168397443-acfe186d-f703-4823-b83f-cb070800da5a.png)
Debug de la commande
```
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] writing data: b'ZIA++DIM A8 RTS\n\r'
2022-05-13 23:38:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
DEBUG (MainThread) [custom_components.rfplayer] Rfplayer send command for {'command': 'DIM A8 RTS', 'protocol': '', 'automatic_add': False}
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] writing data: b'ZIA++DIM A8 RTS\n\r'
```
ou autres en mode RAW ([ici DIM A8 RTS %48]()) ATTENTION protocole doit être '' [passage en mode YAML]
![image](https://user-images.githubusercontent.com/97252459/168397588-c425f2a7-a659-442f-9bcf-1b70c3396904.png)
Mode YAML
```
service: rfplayer.send_command
data:
  command: DIM A8 RTS %48
  protocol: ''
```
Debug de la commande
```
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] writing data: b'ZIA++DIM A8 RTS %48\n\r'
2022-05-13 23:38:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
DEBUG (MainThread) [custom_components.rfplayer] Rfplayer send command for {'command': 'DIM A8 RTS %48', 'protocol': '', 'automatic_add': False}
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] writing data: b'ZIA++DIM A8 RTS %48\n\r'
```

**Comment by cob94440** [comment]
De mon côté la beta 14 ne fonctionne pas
Lorsque je bouge le slider :
![image](https://user-images.githubusercontent.com/62489067/172344190-05165e1f-ff19-4033-aed7-2ae25a43cd7d.png)
et voilà tout ce que j'ai 👍 
![image](https://user-images.githubusercontent.com/62489067/172344321-053e3ee0-ba85-47d7-acf7-4c3c8a89e6d6.png)

**Comment by daafunky** [comment]
Merci doubledom pour ce dev, je vais tester cette beta avec HA sur des controles Chacon/DiO, je peux aider pour tester des volets X2D deltadore, (j'avais fait évoluer la beta sur domoticz). Et il y a aussi le protocole de Cherubini que j'aimerais bien faire fonctionner sur HA pour un store banne, ils utilisent un rollingcode sur du 433mhz.

**Comment by Doubledom45** [comment]
Salut
N'hesite pas à regarder la[ béta ici](https://github.com/Doubledom45/HA-Rfplayer-Beta) .
Les Chacon/Dio remontent bien.
Pour X2D fais remontés tes logs sur la béta.
Pour ce qui est du rollingcode, normalement pas facile ( dire impossible) .
Laisse tes infos sur la béta ou sur le [forum HA Fr](https://forum.hacf.fr/t/utilisateur-rfplayer-version-beta/8649)
@+Dom![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)

**Comment by daafunky** [comment]
> Pour X2D fais remontés tes logs sur la béta.
Peux tu indiquer où se trouvent ces logs ? J'ai activé le mode avancé, mais je n'ai rien dans Paramètres - Système - Journaux

**Comment by seymourd** [comment]
Hello,

J'ai le même problème de création automatique d'entités que déjà reporté sur HACF [ici](https://forum.hacf.fr/t/utilisateur-rfplayer-version-beta/8649/167).
J'ai pu tester de mon côté, en RTS pas de problème pour la création d'entité, ça ne se produit qu'en X2DSHUTTER.

Si ça peut apporter une information supplémentaire pour la résolution...

En tout cas merci pour le boulot, j'ai moi aussi pu sortir ma VM Jeedom qui ne servait qu'à ça, il ne me manque plus que l'intégration de l'entité de mon volet roulant X2D !

**Comment by Doubledom45** [comment]
> Hello,
> 
> J'ai le même problème de création automatique d'entités que déjà reporté sur HACF [ici](https://forum.hacf.fr/t/utilisateur-rfplayer-version-beta/8649/167). J'ai pu tester de mon côté, en RTS pas de problème pour la création d'entité, ça ne se produit qu'en X2DSHUTTER.
> 
> Si ça peut apporter une information supplémentaire pour la résolution...
> 
> En tout cas merci pour le boulot, j'ai moi aussi pu sortir ma VM Jeedom qui ne servait qu'à ça, il ne me manque plus que l'intégration de l'entité de mon volet roulant X2D !

Salut...
Est-ce que tu peux me contacter sur HACF avec [la ref d'ici](https://github.com/gce-electronics/HA_RFPlayer/issues/10#issuecomment-1295010801) ? en me montrant les logs que tu as en ce moment sur le X2D.
![bitmoji](https://sdk.bitmoji.com/render/panel/9d438724-a1e5-44b9-9172-377503bbffe6-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)
**[Doubledom HACF en cours](https://forum.hacf.fr/t/utilisateur-rfplayer-version-beta/8649/212)**

**Comment by seymourd** [comment]
Hello,

Désolé je n'ai pas eu le temps de te faire un retour (ni de m'inscrire sur HACF...) 
Pour la mise à jour Beta 16, il faut désinstaller/réinstaller le composant, ou juste updater le dossier rfplayer suffit ?

Merci !

**Comment by Doubledom45** [comment]
Salut..
La logique veut que l'on désinstalle la précédente version proprement par le menu de l'addon
![image](https://user-images.githubusercontent.com/97252459/199989137-bc5ee7d9-aca1-4168-8dbc-a7af7954e5b6.png)
Redémarré HA, vérifier le répertoire dans ![image](https://user-images.githubusercontent.com/97252459/199989383-e03793dc-532a-4e7e-91da-f10ceec6ec5e.png) si plus de trace de rfplayer![image](https://user-images.githubusercontent.com/97252459/199989503-33b6102c-fa47-4a3a-bb95-7a53a1f24bee.png)
Sinon supprimer voir ![image](https://user-images.githubusercontent.com/97252459/199989825-81894e52-a3ca-4554-baee-a6329300e4f0.png) ![image](https://user-images.githubusercontent.com/97252459/199989703-8604dca5-b7f5-4873-b438-c44dc1bc2870.png)
Et rechercher dans HACS si possible l'addon

Voir info https://github.com/Doubledom45/HA_Rfplayer_Beta

![bitmoji](https://sdk.bitmoji.com/render/panel/09b05e2f-bc63-4d2c-b6e2-baa6e39baa54-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)

**Comment by seymourd** [comment]
Hello,

Merci pour les infos.
J'ai bien fait toutes les MàJ, pourtant toujours la même erreur à l'ajout d'une entité X2DSHUTTER...

**Comment by Doubledom45** [comment]
Est-ce que tu peux passer sur la [discussion de la béta](https://github.com/Doubledom45/HA_Rfplayer_Beta/discussions)
Ou sur le forum [HA Fr](https://forum.hacf.fr/t/utilisateur-version-beta-en-cours-16/8649/215)  et envoyer message en MP
@+
