### ISSUE TITLE
ajout manuel du chemin vers le devices rfplayer

### ISSUE THREAD

**Issue by dkmatt0** [gce-electronics/HA_RFPlayer#16]
Bonjour !

![image](https://user-images.githubusercontent.com/5724752/174438987-2cbe491a-c79d-4291-ac95-ccd620ae7aeb.png)

Le problème est le suivant : J'utilise HA avec docker, et pour ne pas être en mode privileged, je ne monte que les devices que j'ai besoin en les renommant comme par exemple /dev/zigbee, /dev/sms ou /dev/rfplayer. Mais du coup, le component n'a l'air de reconnaître que les devices en /dev/tty*.

Du coup, serait-il possible d'ajouter la possibilité de taper soit-même le chemin vers le devices (s'il ne trouve aucun devices par exemple) ?

C'est clairement pas urgent évidemment (j'ai renommer mon device /dev/ttyUSBrfplayer et ça passe).

Merci d'avance.

**Comment by Aohzan** [comment]
Sera possible via https://github.com/gce-electronics/HA_RFPlayer/pull/36
