### ISSUE TITLE
Suite à la maj ha core 2022.7.1 RFplayer ne fonctionne plus

### ISSUE THREAD

**Issue by jodomi** [gce-electronics/HA_RFPlayer#17]
Bonjour, Je suis passé en Core Home Assistant 2022.7.0 et HA_RFplayer ne fonctionne plus:

Error doing job: Task exception was never retrieved
             File "/config/custom_components/rfplayer/rflib/rfpprotocol.py", line 186, in __init__
                self._event = asyncio.Event(loop=self.loop)
              File "/usr/local/lib/python3.10/asyncio/locks.py", line 168, in __init__
                super().__init__(loop=loop)
              File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
                raise TypeError(
            TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary

Error adding entities for domain number with platform rfplayer
 custom_components.rfplayer.number::RfplayerJammingNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

Que cela soit avec la version stable ou avec la dernière  beta. Il semble que le nouveau noyau core 2022.7.1 soit incompatible avec l'addon HA_RFPlayer (ou l'inverse):
Je n'ai donc plus la détection du RFPlayer. Si je reviens en 2022.6 tout redevient normal.
Merci.
Si vous avez besoin de tester n'hésitez pas.

**Comment by Aohzan** [comment]
Fix en 0.4.0
