### ISSUE TITLE
Mise à jour suite deprecated NumberEntity Home Assistant Core 2022.10

### ISSUE THREAD

**Issue by Doubledom45** [gce-electronics/HA_RFPlayer#19]
Bonjour,
Suite à la demande De HA pour la version 2022.10 avec les erreurs log suivantes 
```
Entity None (<class 'custom_components.rfplayer.number.RfplayerJammingNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.
11:44:19 – (AVERTISSEMENT) Nombre

custom_components.rfplayer.number::RfplayerJammingNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
11:44:18 – (AVERTISSEMENT) Nombre
```

Voir pour modifier le fichier "number.py"
J'ai fait la modification sur la version Béta .
Un pull requests pour ta version ?
@+Dom![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)

**Comment by Aohzan** [comment]
Salut,
oui tu peux faire une PR pour, mais tu peux aussi faire une PR pour toutes tes modifs non ?

**Comment by Doubledom45** [comment]
Pour le NumberEntity OK.

Pour la PR de la Béta, je ne sais pas trop, j'attends toujours des retours sur le Visionic .
A toi de voir si on fait ou pas ?
@+Dom![bitmoji](https://sdk.bitmoji.com/render/panel/9d438724-a1e5-44b9-9172-377503bbffe6-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)
