### ISSUE TITLE
initial setup

### ISSUE THREAD

**Issue by stijn001** [gce-electronics/HA_RFPlayer#21]
Is there someone who could write a simple user manual for RF Player on HA please? 

I'm trying to add 4 Franciaflex covers to HA

So far, I figured out that if you ‘auto-add’ your devices you get some sensor entities.
This sensor entity also marks the protocol and ID of the device.
If I use rfplayer.send_command in a script, this results in a switch being created.
But HA doesn’t transmit any command to the RF Player. 
Do I use the right protocol ? [8 for X2D ?]
Do I use the right command? [1 for cover UP; 2 for cover DOWN ?]
What’s the difference between Device Address and Device ID ?

Thx for helping me out.
Stijn

**Comment by Doubledom45** [comment]
Hello,
First of all, I'm French, not very good at your language, I use Google translator.
Could you test the [Beta version of HA_Rfplayer](https://github.com/Doubledom45/HA_Rfplayer_Beta)  ?
And upload the logs to the [Forum io](https://community.home-assistant.io)  or [fr de HA](https://forum.hacf.fr)  nickname Doubledom

Français
Bonjour,
D'abord je suis français pas très doué dans votre langue, je passe par Google traducteur.
Pouvais vous tester la version [Béta de HA_Rfplayer](https://github.com/Doubledom45/HA_Rfplayer_Beta) ?
Et faire remonter les logs sur le [Forum io](https://community.home-assistant.io) ou [fr de HA] (https://forum.hacf.fr) pseudo Doubledom
[@+Dom]()
![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)
