### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ylemoigne** [gce-electronics/HA_RFPlayer#24]
Hello,

On startup, home assistant say : `WARNING (MainThread) [homeassistant.components.number] custom_components.rfplayer.number::RfplayerJammingNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

And : `WARNING (MainThread) [homeassistant.components.number] Entity None (<class 'custom_components.rfplayer.number.RfplayerJammingNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.`

**Comment by Doubledom45** [comment]
Version HA ?
Problème résolu depuis 09/22
Voir votre version addon ou la [béta](https://github.com/Doubledom45/HA_Rfplayer_Beta)

**Comment by ylemoigne** [comment]
La version de l'addon est sur la dernière release (0.4.0), qui effectivement date d'avant le 09/22.
