### ISSUE TITLE
Multiple errors following update Home assistant core > 2024.3.0

### ISSUE THREAD

**Issue by Excusebouts** [gce-electronics/HA_RFPlayer#37]
![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/37b1dc7a-a2d4-4b02-8058-74ae2970d812)

![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/09322dd7-e7f9-47cc-9775-a4e6681ddfca)

![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/47e63076-7df7-4a81-b9d3-7e1a1b99caaa)

![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/8dcdf4b2-b73a-46a3-8e16-4be08c9a66b6)

![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/12fd0375-d8af-4b56-b705-ea0400380d89)

![image](https://github.com/gce-electronics/HA_RFPlayer/assets/5636586/f517d00f-1b66-4a1a-84b9-6000c17f2082)

**Comment by Aohzan** [comment]
0.7.0 sorti

**Comment by Excusebouts** [comment]
C'est ok avec la 0.7.0 ;-)

Merci.
