### ISSUE TITLE
The configuration flow could not be loaded: [object Object]

### ISSUE THREAD

**Issue by chma31** [gce-electronics/HA_RFPlayer#4]
Bonjour,

quand j'essaie de rajouter cette intégration GCE RFplayer j'obtiens le message d'erreur "Le flux de configuration n'a pas pu être chargé : [object Object]".
J'utilise HA OS 2022.2.5 sur un Raspberry Pi. Je l'ai éteins, inséré le dongle puis rallumé.
Voilà ce que j'ai dans le journal :
![image](https://user-images.githubusercontent.com/96373325/153369503-667a6a02-0dc9-47f5-9a95-c7c75a6a8d5a.png)

Toute idée ou suggestion est la bienvenue.

PS : il serait peut-être judicieux de rajouter quelque part qu'il faut uniquement utiliser des minuscules pour rechercher une intégration. Cela faciliterait la vie de néophytes comme moi qui a passé des heures avant de trouver ce qui n'allait pas.

**Comment by Aohzan** [comment]
bonjour,
les fichiers n'ont pas été récupéré correctement, tu peux utiliser le boutons suivants
![image](https://user-images.githubusercontent.com/2736322/153373714-8c7280c6-12de-4c80-ac76-529939201d9a.png)

pour l'histoire des minuscules je n'ai pas compris le soucis

**Comment by chma31** [comment]
Bonjour,
merci pour la réponse rapide.
Je pensais avoir déjà fait cette manip avec le fichier .zip mais visiblement ce n'était pas le cas. Bilan, en refaisant le download, ça marche.
Par contre, dans la partie "release" et dans ce fichier zip, il n'y a pas les dernières améliorations apportées sur le jamming, non ?
De plus, quelle est la version ? Le fichier manifest.json stipule "0.2.0".

Pour les minuscules, c'était très simple : si je rentrais "GCE" pour chercher une intégration, HA ne trouvait rien, il fallait obligatoirement des minuscules. Maintenant les deux fonctionnent. Je ne sais ce qui a changé.

Super travail d'avoir intégré le RFplayer dans HA.

**Comment by Aohzan** [comment]
L'implémentation du jamming et autres sont pas encore finalisées, je ferais une release à ce moment, cependant en prenant via le Download ZIP, tu dois les avoir (mais ça fonctionne pas encore bien)
