### ISSUE TITLE
Intégration Somfy RTS partielle

### ISSUE THREAD

**Issue by christoff4444** [gce-electronics/HA_RFPlayer#5]
Bonjour,

Avant tout, un grand merci pour cette intégration de RFPlayer sur HA, c'était mon dernier frein pour passer de Domoticz à HA.

Mes volets Somfy RTS étaient déjà couplés à mon RFPlayer (j'avais utilisé le logiciel en JAVA fourni par le constructeur).
J'ai fait l'intégration de mes volets Somfy RTS en reprenant les devices ID que j'avais utilisés.
Le soucis, c'est qu'une fois intégrés, je n'ai que les commandes "ON" et "OFF".
Les commandes possibles pour les SOMFY RTS sont :
 - ON
 - OFF
 - DIM ==> permet de stopper l'ouverture/fermeture en cours, ou de mettre le volet dans une position prédéfini si le volet est à l'arrêt (touche "MY" des télécommandes SOMFY RTS)
 - ASSOC ==> Permet l'association entre un device ID choisi, sur le RFPlayer, et le(s) volets SOMFY RTS
 - DISSOC ==> Permet dissociation entre un device ID choisi, sur le RFPlayer, et le(s) volets SOMFY RTS

Merci d'avance !

**Comment by christoff4444** [comment]
Top, merci beaucoup !
Je testerai demain ;-)

**Comment by Doubledom45** [comment]
Bonjour
La commande MY correspond à un DIM %4, les commandes sont acceptées par le plugin en béta, intégration en cours.
la commande du MY doit être ici pour A14:
```
service: rfplayer.send_command
data:
  command: DIM %4
  protocol: RTS
  device_address: A14
  automatic_add: true
```
Toujours pour l'instant comme en mode dev, pour ASSOC (et DISSOC) les commandes passent aussi, les switch seront créés avec leurs infos de l'adresse ici `switch.rts_a14` bien sûr il faut que le store soit en mode association avant d'envoyer la commande, pour que celui-ci corresponde à ce switch.
![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-a706a5f6-b477-4dc3-af74-948a7e88e9e9-v1.png?transparent=1&palette=1&width=246)

**Comment by Doubledom45** [comment]
**_Voir Béta 16_**
(lhttps://github.com/Doubledom45/HA_Rfplayer_Beta)
