### ISSUE TITLE
Unknown CHACON & PARROT Sensors

### ISSUE THREAD

**Issue by chma31** [gce-electronics/HA_RFPlayer#6]
Bonjour,
en plus des entités "switch" créés automatiquement lorsque j'ai envoyé les commandes pour piloter mes prises DIO, des entités "sensor" sont apparues. Je peux les désactiver, ce n'est pas bloquant du tout.
Mais ont-elles une signification / utilité ? Je n'ai pas réussi à déterminer s'il y avait une signification pour leur état (0 ou 1) ou une corrélation avec une quelconque action.
Ai-je fait une erreur ?
![image](https://user-images.githubusercontent.com/96373325/153831351-057f549a-822f-43b6-ba79-b5f3f16ea050.png)

Super boulôt d'intégration, bravo.

Cordialement.

**Comment by Aohzan** [comment]
Il ne s'agit pas d'entités créées quand une télécommande est utilisée pour piloter les prises ?

**Comment by chma31** [comment]
Effectivement, après test ce sont les informations captées par le RFplayer remontées dans HA. Cela permet de visualiser l'état des prises même si elles ont été pilotées en direct avec une télécommande.
Merci bien.
