### ISSUE TITLE
Unable to command device previously registered under device address BX

### ISSUE THREAD

**Issue by ylemoigne** [gce-electronics/HA_RFPlayer#97]
### System Health details

More a usage issue than a technical one.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

In RFPlayer 0.7.0, I had somfy RTS shutter binded to address B1

As RFPlayer 1.0.0 request decimal value, I tried the following adress in `Add RF Device` :
16,
17,
20,
160,
176

Without success so far.

### Reproduction steps

ASSOC an RTS shutter under B1 in RFPlayer 0.7.0
Upgrade RFPlayer to 1.0.0
Try to recreate a device that send command to previously B1 address

### Debug logs

```text
This is more a usage issue than a technical/implementation one.
I think that logs won't be helpfull
```

**Comment by racletteparty** [comment]
In the spec ID 16 is supposed to be the same as B1. Maybe you can try the send command service to confirm that it works with B1 address instead of ID 16.

**Comment by racletteparty** [comment]
I think it's bug in the way addresses are processes
https://github.com/gce-electronics/HA_RFPlayer/blob/32f0e260a240e0474b6a0fcbdffd1cca18c221bd/custom_components/rfplayer/rfplayerlib/device.py#L73

It doesn't work with address >15
I will try to fix it

**Comment by ylemoigne** [comment]
Thanks you !

**Comment by racletteparty** [comment]
Use now 0xff mask on addresses to send commands.
